.TH "GIT\-SELECT\-INTERACTIVE" "1" "April 2020" "" ""
.SH "NAME"
\fBgit-select-interactive\fR \- Interactive mode for git add
.SH SYNOPSIS
.P
.RS 2
.nf
git select\-interactive [\-\-reset|\-\-stash]
git select\-interactive \-\-help
git select\-interactive \-\-version
.fi
.RE
.SH DESCRIPTION
.P
Select files to stage with interactive cli\. Use arrows to navigate, <space> to select, <a> to toggle all\.
.SH OPTIONS
.SS \-\-reset, \-r
.P
Select files to unstage
.SS \-\-stash, \-s
.P
Select files to stash
.SS \-\-help, \-h
.P
Show help
.SS \-\-version, \-v
.P
Show version
.SH Author
.P
Ivan Rossi \fIhttps://github\.com/ivanross\fR

